Test Failed at none:1
  Expression: square!(5) == 20
   Evaluated: 25 == 20
Test.FallbackTestSetException("There was an error during testing")
